CREATE TABLE pessoa
(
  pessoaID INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  sexo char(1) NOT NULL, -- 1->crédito, 2->débito, 3->ambos
  cidade VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  dtCad DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dtAlt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) engine=InnoDb;